# Site settings
title: NotAlone, U Are!
description: "NotAlone blog, by Edward."
disqus_shortname: uare
reading_time: true
words_per_minute: 300
baseurl: ""
# url: "http://uare.github.io"
image_url: "/images"
index_image: "images/feature-image-index.jpg"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:title

# Amount of post to show on home page
paginate: 5

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: shell

# Analytics and webmaster tools stuff goes here
google_analytics: UA-74320749-1
google_verify: googlefdf93594e52ab258.html
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Background image to be tiled on all pages
background: 

# Owner/author information
owner:
  name: Edward Green
  avatar: avatar.jpeg
  bio: "自由 发现 记录</br>Freedom Discovery Notes"
  github: zhendongguan
  twitter: zhendongguan
  instagram: zhendongguan
  email: zhendongguan@gmail.com
  facebook:       
  stackexchange:  
  linkedin:       
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus: +关振东

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
sass:
  sass_dir: _sass
  style: compressed

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
