# Site settings
title: NotAlone, U Are!
description: NotAlone blog, by Edward.
disqus_shortname: uare
reading_time: true
words_per_minute: 300
baseurl: ""
# url: "http://uare.github.io"
image_url: "/images"
index_image: "images/feature-image-index.jpg"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:title

# Amount of post to show on home page
paginate: 5

# Analytics and webmaster tools stuff goes here
google_analytics: UA-74320749-1
google_verify: googlefdf93594e52ab258.html
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 0A9D205EBE862882573E09E232A3135E

# Background image to be tiled on all pages
background:

# Owner/author information
owner:
  name: Edward Guan
  avatar: avatar.jpeg
  # bio: 自由 发现 记录
  bio: Freedom Discovery Notes
  github: nooop3
  twitter: ludewan
  instagram: ludewan
  email: zhendongguan@outlook.com
  facebook:
  stackexchange:
  linkedin:
  flickr:
  tumblr:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
future: true
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  hard_wrap: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: shell

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
